home: Home
archives: Archives
about: About
categories: Categories
series: Series
search: Search
searchPlaceHolder: Input Search key Words Here
tags: Tags
tagcloud: Tag Cloud
video: Video
help: Help
links: Links
photo: Photos
book: Reading
music: Music
cloud: Resource
prev: <i class="iconfont icon-back"></i>
next: <i class="iconfont icon-right"></i>
comment: Comment
page: No. %d Pages
recent_posts: Recent Posts
newer: Newer
older: Older
share: Share
theme_by: Theme by
rss_feed: RSS Feed
category: Category
tag: Tag
connect: 'Connect With Me'
post_total_count: There are %d posts in total till now.
read_more: Continue Reading →
contents: Contents

none: 无
insight:
    hint: 'Type something...'
    posts: 'Posts'
    pages: 'Pages'
    categories: 'Categories'
    tags: 'Tags'
    untitled: '(Untitled)'

#category
技术:
    zh: 野生技术协会
    en: Geek – Only for Love
    img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/banner/coding.jpg
学术:
    zh: 野生技术协会
    en: Geek – Only for Love
    img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/banner/coding.jpg
生活:
    zh: 生活
    en: live
    img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/banner/writing.jpg

#tag
悦读:
    img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/banner/reading.jpg